name: Build QMK firmware
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@qmk-userspace
    with:
      qmk_repo: qmk/qmk_firmware
      qmk_ref: master

  publish:
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@qmk-userspace
    if: always() && !cancelled()
    needs: build
