name: Build QMK firmware
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        oled:
          - "yes"
          - "no"
# List of keymap json files to build
        file:
        - crkbd.json
# End of json file list

    steps:

    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: rhruiz/qmk_firmware
        ref: refs/heads/fix/mk_precedence
        submodules: recursive

    - name: Checkout userspace
      uses: actions/checkout@v3
      with:
        path: users/${{ github.actor }}

    - name: Build firmware
      env:
        OLED_ENABLE=${{ matrix.oled }}
      run: qmk compile "users/${{ github.actor }}/${{ matrix.file }}" -e OLED_ENABLE=${OLED_ENABLE} -e OLED_ROTATE_ENABLE=yes

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        name: ${{ matrix.file }}_${{ github.actor }}
        path: |
          *.hex
          *.bin
          *.uf2
