name: Build QMK firmware - corne and lily58
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        include:
          - keyboard: crkbd/rev1
            oled: "yes"

          - keyboard: crkbd/rev1
            oled: "no"

          - keyboard: lily58/rev1
            oled: "yes"
    steps:
    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout userspace
      uses: actions/checkout@v4
      with:
        token: ${{ github.token }}
        submodules: recursive

    - name: Check if qmk_firmware exists
      id: check_files
      uses: andstor/file-existence-action@v3
      with:
        files: qmk_firmware

    - name: Checkout QMK
      uses: actions/checkout@v4
      if: steps.check_files.outputs.files_exists == 'false'
      with:
        token: ${{ github.token }}
        repository: qmk/qmk_firmware
        ref: refs/heads/master
        submodules: recursive
        path: qmk_firmware

    - name: Install QMK CLI
      run: |
        python3 -m pip install --upgrade qmk
        python3 -m pip install -r qmk_firmware/requirements.txt

    - name: Configure QMK CLI
      run: |
        qmk config userspace_compile.parallel=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null)
        qmk config user.qmk_home=$GITHUB_WORKSPACE/qmk_firmware
        qmk config user.overlay_dir=$GITHUB_WORKSPACE

    - name: Build firmware
      env:
        QMK_HOME: "${{ github.workspace }}/qmk_firmware"
        OLED_ENABLE: ${{ matrix.oled }}
      run: |
        qmk compile -km "${{ github.actor }}" -kb "${{ matrix.keyboard }}" -e OLED_ENABLE=${OLED_ENABLE} -e OLED_ROTATE_ENABLE=yes || touch .failed
        # Generate the step summary markdown
        ./qmk_firmware/util/ci/generate_failure_markdown.sh > $GITHUB_STEP_SUMMARY || true
        # Truncate to a maximum of 1MB to deal with GitHub workflow limit
        truncate --size='<960K' $GITHUB_STEP_SUMMARY || true
        # Exit with failure if the compilation stage failed
        [ ! -f .failed ] || exit 1

    - name: Archive firmware
      uses: actions/upload-artifact@v4
      if: always() && !cancelled()
      continue-on-error: true
      with:
        name: Firmware-${{ matrix.keyboard }}-${{ matrix.oled }}-oled
        path: |
          *.hex
          *.bin
          *.uf2
